name: locator

environment:
  sdk: ^3.4.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  search:
    path: ../

  remote:
    path: ../remote

  data:
    path: ../data

  domain:
    path: ../domain

  dio: ^5.7.0
  get_it: ^8.0.0

dev_dependencies:
  flutter_lints: ^4.0.0