name: search
description: "자비스앤빌런즈 과제 입니다."

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  data:
    path: data
    
  local:
    path: local

  remote:
    path: remote

  locator:
    path: locator

  domain:
    path: domain

  cupertino_icons: ^1.0.8

  flutter_bloc: ^8.1.6
  bloc_test: ^9.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true